### ISSUE TITLE
QGIS 3.30 - TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 

### ISSUE THREAD

**Issue by Scintsz** [sandroklippel/cbers4a#5]
Hi, I just updated QGIS to version 3.30 and got the following error:

TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/aperius/AppData/Roaming/QGIS/QGIS3\profiles\APK/python/plugins\cbers4a\__init__.py", line 39, in classFactory
    return Cbers4aDownloader(iface)
  File "C:\Users/aperius/AppData/Roaming/QGIS/QGIS3\profiles\APK/python/plugins\cbers4a\qgis_cbers4a_downloader.py", line 79, in __init__
    self.footprint = QgsRubberBand(iface.mapCanvas(), True)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

Must be something to do with the new version.

**Comment by phborba** [comment]
Hi @sandroklippel ! I've fixed this issue in the pull request #6 . Thank you for your work in the plugin!

**Comment by sandroklippel** [comment]
Thank you for your contribution. I merged into the main branch.
